import '../node_modules/normalize.css/normalize.css';
import './styles.css';
import './components/footer/styles.js';
import './components/developers/js/index';
// import './components/developers/modal-window/dev-modal';
// import './components/developers/modal-window/dev-styles.css';
// import './components/hero/slider-item/slider-item';
// import './components/header/js/header';
// import './components/header/js/newAdv';
// import './components/modal/modalBackDrop.js';
// import './components/card/index';
// import './components/catalog/categories-list-item/index.js';
// import './components/loader/index';
// import './components/auth/auth';
// import './components/auth/accCabinet';
